# Generated by Django 2.1.2 on 2018-11-28 01:09
import base64

from django.db import migrations

from users.models import User


def create_initial_user(apps, schema_editor):
    User.objects.create_superuser(
        username='admin',
        password=base64.b64decode('MTIzNDU2'.encode()).decode(),
    )



class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_user)
    ]
