# Generated by Django 5.2.1 on 2025-06-02 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guardians',
            field=models.ManyToManyField(blank=True, help_text='Responsáveis ligados a essa criança', related_name='kids', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('guardian', 'Responsável'), ('kid', 'Criança')], help_text='Selecione o tipo de usuário', max_length=10, verbose_name='Tipo de usuário'),
        ),
    ]
#coisas 
