services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: taskids
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 10203040
    ports:
      - "5433:5432"

  web:
    build: .
    command: /code/entrypoint.sh
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: taskids
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_forte_aqui
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DEBUG: "False"
      ALLOWED_HOSTS: "seudominio.com,www.seudominio.com"

volumes:
  postgres_data:
  static_volume:
  media_volume:
