# Generated by Django 5.2.1 on 2025-05-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childreward',
            options={'verbose_name': 'Recompensa da Criança', 'verbose_name_plural': 'Recompensas das Crianças'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'Recompensa', 'verbose_name_plural': 'Recompensas'},
        ),
    ]
